// integracao-react/src/componentes/Contador.tsx
import React, { Component } from 'react';
import ContadorValor from './ContadorValor';
import logRender from '../decorators/logRender';

interface IContadorProps {
    valorInicial?: number;
}

interface IContadorState {
    valor: number
}

@logRender
export default class Contador extends Component<IContadorProps, IContadorState> {

    public state = { valor: this.props.valorInicial || 0 }

    private setValor = (delta: number) => {
        this.setState({
            valor: this.state.valor + delta
        })
    }

    render() {
        return(
            <div>
                <ContadorValor contador={this.state.valor} />
                <button onClick={() => this.setValor(10)}>+</button>
                <button onClick={() => this.setValor(-10)}>-</button>
            </div>
        )
    }
}

// integracao-vue/src/componentes/Contador.vue
<template>
  <div>
      <h1>Contador</h1>
      <h2>{{ valor }}</h2>
      <button @click="setValor(-1)">Dec</button>
      <button @click="setValor(1)">Inc</button>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
    props: {
        valorInicial: {
            type: Number
        }
    },
   data() {
       return {
           valor: this.valorInicial || 0
       }
   },
   methods: {
       setValor(delta: number) {
           this.valor += delta
       }
   }
})
</script>

<style>

</style>
